# Generated by Django 3.0.6 on 2020-05-16 04:34

from django.db import migrations, models
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productdetailpage_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailpage',
            name='image',
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='images',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='inStock',
            field=models.BooleanField(help_text='Con hang', null=True),
        ),
    ]
