# Generated by Django 3.0.6 on 2020-05-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200516_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailpage',
            name='brief',
            field=models.CharField(help_text='Mo ta ngan gon', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='weight',
            field=models.CharField(help_text='Trong luong', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productdetailpage',
            name='inStock',
            field=models.BooleanField(help_text='Con hang ?', null=True),
        ),
        migrations.AlterField(
            model_name='productdetailpage',
            name='name',
            field=models.CharField(help_text='Ten san pham', max_length=100),
        ),
    ]
