# Generated by Django 3.0.6 on 2020-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200516_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailpage',
            name='brief',
            field=models.CharField(help_text='Mo ta ngan gon', max_length=500, null=True),
        ),
    ]
