# Generated by Django 3.0.6 on 2020-06-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200516_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailpage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='productlistingpage_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.ProductListingPage'),
            preserve_default=False,
        ),
    ]
