# Generated by Django 3.0.6 on 2020-06-01 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('product', '0006_auto_20200601_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailpage',
            name='productlistingpage_ptr',
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=123, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
    ]
