# Generated by Django 3.0.6 on 2020-06-02 14:24

from django.db import migrations
import home.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200601_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlistingpage',
            name='description',
            field=wagtail.core.fields.StreamField([('richtext_block', home.blocks.RichtextBlock())], blank=True),
        ),
    ]
