# Generated by Django 3.0.6 on 2020-06-22 15:08

from django.db import migrations, models
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productlistingpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailpage',
            name='brief',
            field=models.CharField(blank=True, help_text='Mo ta ngan gon', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productdetailpage',
            name='description',
            field=wagtail.core.fields.StreamField([('title_block', wagtail.core.blocks.CharBlock()), ('richtext_block', home.blocks.RichtextBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetailpage',
            name='inStock',
            field=models.BooleanField(default=True, help_text='Con hang ?', null=True),
        ),
    ]
