# Generated by Django 3.0.6 on 2020-05-13 15:58

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', wagtail.core.fields.StreamField([('richtext_block', home.blocks.RichtextBlock())], blank=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Trang chu',
                'verbose_name_plural': 'Trang chu',
            },
        ),
    ]
