# Generated by Django 3.0.6 on 2020-05-13 16:04

from django.db import migrations, models
import home.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_welcometag'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcometag',
            name='name',
            field=models.CharField(help_text='Product name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='welcometag',
            name='description',
            field=wagtail.core.fields.StreamField([('richtext_block', home.blocks.RichtextBlock())], null=True),
        ),
    ]
