# Generated by Django 3.0.6 on 2020-05-14 17:27

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.StreamField([('richtext_block', home.blocks.RichtextBlock())], blank=True)),
            ],
            options={
                'verbose_name': 'Gioi thieu',
            },
            bases=('wagtailcore.page',),
        ),
    ]
